In [266]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler,MinMaxScaler,OneHotEncoder
#from sklearn.compose import ColumnTransform
#from sklearn.pipeline import Pipeline
#from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest,f_regression,f_classif
#from sklearn.decomposition import PCA

In [267]:
df=pd.read_csv("/content/covid_toy.csv")

display(df.head())

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [268]:
print(df.dtypes)

age            int64
gender        object
fever        float64
cough         object
city          object
has_covid     object
dtype: object

In [269]:
numeric_columns=df.select_dtypes(include=np.number).columns

print("Numeric Columns:")
print(numeric_columns)

Numeric Columns:
Index(['age', 'fever'], dtype='object')

In [270]:
categorical_columns=df.select_dtypes(include="object").columns

print("Categorical Columns:")
print(categorical_columns)

Categorical Columns:
Index(['gender', 'cough', 'city', 'has_covid'], dtype='object')

In [271]:
df["city"]=df['city'].astype("object")

In [272]:
print(df.isnull().sum())

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [273]:
df["fever"]=pd.to_numeric(df["fever"])

In [274]:
df["fever"]=df["fever"].fillna(df["fever"].mean())

In [275]:
print(df.isnull().sum())

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [276]:
print(df.isnull().sum())

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [277]:
scaler=MinMaxScaler().set_output(transform="pandas")

scaled_data=scaler.fit_transform(df[numeric_columns])

scaled_data.head()

        age     fever
0  0.696203  0.833333
1  0.278481  0.333333
2  0.468354  0.500000
3  0.329114  0.000000
4  0.759494  0.500000

In [278]:
categorical_columns=["fever","has_covid"]

In [279]:
encoder=OneHotEncoder(drop="first").set_output(transform="pandas")

encoded_data=encoder.fit_transform(df[categorical_columns])

encoded_data.head()

,fever_99.0,fever_100.0,fever_100.84444444444445,fever_101.0,fever_102.0,fever_103.0,fever_104.0,has_covid_Yes
0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [280]:
X = df.drop("fever_99.0, axis=1")
y = df["fever_99.0"]

In [281]:
X_numeric = X.select_dtypes(include=np.number)

selector = SelectKBest(
    score_func=f_regression,
    k=5
).set_output(transform="pandas")

X_selected=selector.fit_transform(X_numeric, y)

print(X_selected.head())

   fever_100.0  fever_100.84444444444445  fever_101.0  fever_102.0  \
0          0.0                       0.0          0.0          0.0
1          1.0                       0.0          0.0          0.0
2          0.0                       0.0          1.0          0.0
3          0.0                       0.0          0.0          0.0
4          0.0                       0.0          1.0          0.0

   fever_104.0
0          0.0
1          0.0
2          0.0
3          0.0
4          0.0